### ISSUE TITLE
Does password mode support id_token?

### ISSUE THREAD

**Issue by weijie0** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#14]
I use password mode. Do you support id_token?
thanks

**Comment by Basit-Mahmood** [comment]
@luanweijie  Hmm if you mean to support request parameter of name id_token. Then I would say no. Actually Password grant type normally have grant_type, username, password and scope request parameters. So I just included those. But as it's a demo project. You can add it in your own code. 

In-fact there are additional parameters too in the OAuth2ResourceOwnerPasswordAuthenticationToken. May be you can check it  and see if it contains any additional parameter and take some action.

But I am not sure whether this is really what you are asking for ?

This project is a demo project which shows you how you can set authorization server and add additional grant types in it. In-fact when I made it. My thought was to create a ready to use sample for every one. That's why I put everything in this project like internationalization,  Customize consent, use database user instead of in memory user and etc.  Like in this case password grant type. But if you want to do some stuff with password grant type then you ate free to modify it in your own code.

Other than password grant type this project is same for the samples provided by Spring on each latest release. If it is something that is not related to password grant type then you should ask it on Spring forum. If Spring version 0.3.1 supports id_token then  this project too.

Thanks

**Comment by Basit-Mahmood** [comment]
@luanweijie  Did you solved it ? You closed the issue ?

**Comment by luanweijie** [comment]
> @luanweijie Did you solved it ? You closed the issue ?

no, I think I know what I should do, but haven't tried it yet

**Comment by luanweijie** [comment]
https://github.com/Basit-Mahmood/spring-authorization-server-password-grant-type-support/blob/master/SpringAuthorizationServer/src/main/java/pk/training/basit/oauth2/authentication/OAuth2ResourceOwnerPasswordAuthenticationProvider.java
I think the logic of id_token should be added here, currently only access_token and refresh_token

**Comment by luanweijie** [comment]
If the password is wrong, how to translate the custom exception? Now 401 is returned

**Comment by Basit-Mahmood** [comment]
@luanweijie Can you give me the request and expected response. I have to see how other grant types are doing it. Or does password grant type supports it ? I don't  know exactly. But you can do it in your code. After all the code is all open. And if it works then you can let me know. I would be thankful to you.

Thanks

**Comment by Basit-Mahmood** [comment]
@luanweijie ID token support has been added to password grant type. i.e., in OAuth2ResourceOwnerPasswordAuthenticationProvider.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
No response since long time after adding ID token support. Closing the issue.
