### ISSUE TITLE
Can I upgrade the spring boot version to 3.0.0 and the Spring Authorization Server version to 1.0.0

### ISSUE THREAD

**Issue by ittoyxk** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#17]
Spring Authorization Server version 1.0.0 has been released. I hope it can be updated. Thank you

**Comment by Basit-Mahmood** [comment]
@ittoyxk Yes you can because it is using Java 17. But Authorization Server version 1.0.0 is base on Spring boot 3. And Spring Boot 3.0 is using Spring version 6. 

In Spring Boot 2 we use namespace javax. But in Spring Boot 3 name space change from javax to jakarta. 

I read that there is a migration guide or tool from spring Boot 2.7 to Spring Boot 3.0. But I didn't try that yet. I will be busy for two to three days. After that I will make a repository for Spring Authorization Server 1.0.0 and Spring Boot 3 and migrate the current one with 0.4.0.

But yes you can try. At least the code is using Java 17 which is the baseline for Spring Boot 3. But what are the challenges when you and I will try to migrate this to Spring Boot 3. I don't know :) . 

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
@ittoyxk Spring boot 3 and authorization server 1.0.0 has been available in spring-authorization-server-spring-boot-3 repository

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
Upgraded version is available in spring-authorization-server-spring-boot-3 repository
