### ISSUE TITLE
The Authorization Code showing me an error page

### ISSUE THREAD

**Issue by Sabbir** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#20]
when i logged in from client, then click the Authorization Code
it shows me not found error

can you please help me on this

**Comment by Basit-Mahmood** [comment]
You didn't provide any detail. But was your authorization server was running when you click on Authorization Code in the client ?

Or when you ran your authorization server then may be you got some error in the start. Check the logs when server starts. Due to which authorization server wasn't start properly

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
No response since long time. Closing the issue.
