### ISSUE TITLE
Refreshing the token does not work

### ISSUE THREAD

**Issue by SSDespair** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#3]
Hello, according to your code, it doesn't work when I try to refresh the token in my own code. Have you tried to refresh the token

**Comment by Basit-Mahmood** [comment]
Ah you tried this. I am very glad. Yes it won't  work because in the JwtCustomizerServiceImpl there is a check for grant_type. There shouldn't be check for grant_type. Actually at that time I just focused on the access token and the password grant type implementation. May be that's why I did write the code in this way. But I will modify the code so it will work. But for now you can just put the check in JwtCustomizerServiceImpl for refresh_token and it will work. Thanks :)

**Comment by SSDespair** [comment]
Thank you for your answer. Looking forward to your latest code.

**Comment by SSDespair** [comment]
When I try to modify the code provided by you to make it applicable to the spring authorization server to refresh the token, there are two problems. One is that I can't get the information of map < string, Object > attributes = parsemap (rs.getstring ("attributes") in jdbcoauthauthorizationservice, One problem is that I can't get the authentication information when I get the authorization. Getattribute (principal. Class. Getname()) in oauthrefreshtokenauthenticationprovider. I tried to solve the previous problem. The other problem has been trying to modify. I can't modify it. Do you have any good suggestions to help me.
![image](https://user-images.githubusercontent.com/26852131/141049619-2967b808-c309-43af-baf2-e719a9fb3782.png)
If jwtcustomizer is not used, token and refresh can be returned_ Token.

**Comment by Basit-Mahmood** [comment]
@SSDespair I have done the changes for Refresh token. I also simplified the `JwtCustomizerServiceImpl`. Now there is no check for grant_type. Now it is working for refresh_token gant type too.  Can you please just get the latest code and see if it is working fine or not for refresh token. I updated the dependencies too.  Thanks

**Comment by Basit-Mahmood** [comment]
resolved with #4
